jQuery(document).ready(function($){"use strict";$('a[data-rel]').each(function(){$(this).attr('rel',$(this).data('rel'));});if($('#home-banner').length){$('#home-banner').bxSlider({infiniteLoop:true,auto:true,hideControlOnEnd:true});}
if($('audio').length){$('audio').audioPlayer();}
$('#search-box-form').hide();$('a.btn-search').click(function(){$('#search-box-form').toggle('slide');});$('a.crose').click(function(){$('#search-box-form').toggle('slide');});if($('.countdown').length){$('.countdown').final_countdown();}
$(window).stellar();if($('.defaultCountdown').length){var austDay=new Date();austDay=new Date(austDay.getFullYear()+ 1,1- 1,26);$('.defaultCountdown').countdown({until:austDay});$('#year').text(austDay.getFullYear());}
if($('#timelines-slider').length){$('#timelines-slider').bxSlider({pagerCustom:'#bx-pager'});}
if($('#footer-tweet').length){$('#footer-tweet').bxSlider({mode:'fade',auto:true,captions:true});}
if($('.timeline-page-slider').length){$('.timeline-page-slider').bxSlider({pagerCustom:'#bx-pager'});}
if($('#post-slider').length){$('#post-slider').bxSlider({mode:'fade',autoControls:true});}
if($('#slider1').length){var image_array=new Array();image_array=[{image:'content/our_team/1.jpg',link_url:'content/our_team/1big.jpg',},{image:'content/our_team/2.jpg',link_url:'content/our_team/2big.jpg',},{image:'content/our_team/3.jpg',link_url:'content/our_team/3big.jpg',},{image:'content/our_team/4.jpg',link_url:'content/our_team/4big.jpg',},{image:'content/our_team/5.jpg',link_url:'content/our_team/5big.jpg',},{image:'content/our_team/6.jpg',link_url:'content/our_team/6big.jpg',link_rel:'prettyPhoto'},{image:'content/our_team/7.jpg',link_url:'content/our_team/7big.jpg',}];$('#slider1').content_slider({map:image_array,max_shown_items:7,hv_switch:0,active_item:0,wrapper_text_max_height:450,middle_click:1,under_600_max_height:1200,border_radius:-1,automatic_height_resize:1,border_on_off:0,allow_shadow:0});}
if($('.gallery').length){$(".gallery:first a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'normal',theme:'light_square',slideshow:3000,autoplay_slideshow:true});$(".gallery:gt(0) a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'fast',slideshow:10000,hideflash:true});}
if($('#container').length){$('#container').BlocksIt({numOfCol:4,offsetX:15,offsetY:15});}
if($('.slide-out-div').length){$('.slide-out-div').tabSlideOut({tabHandle:'.handle',pathToTabImage:'images/gear.png',imageHeight:'40px',imageWidth:'40px',tabLocation:'left',speed:300,action:'click',topPos:'189px',fixedPosition:false});}
if($('#map_contact_1').length){var map;var myLatLng=new google.maps.LatLng(48.85661,2.35222);var myOptions={zoom:12,center:myLatLng,zoomControl:true,mapTypeId:google.maps.MapTypeId.ROADMAP,mapTypeControl:false,styles:[{saturation:-100,lightness:10}],}
map=new google.maps.Map(document.getElementById('map_contact_1'),myOptions);var marker=new google.maps.Marker({position:map.getCenter(),map:map,icon:'images/map-icon.png'});marker.getPosition();var infowindow=new google.maps.InfoWindow({content:'',position:myLatLng});infowindow.open(map);}
if($('.accordion-body').length){$('.accordion-body').on('show',function(e){$(e.currentTarget).parent().find('.accordion-heading').addClass('active')})
$('.accordion-body').on('hide',function(e){$(e.currentTarget).parent().find('.accordion-heading').removeClass('active')})}
if($('#flexiselDemo1').length){$("#flexiselDemo1").flexisel({visibleItems:3,animationSpeed:1000,autoPlay:false,autoPlaySpeed:3000,pauseOnHover:true,enableResponsiveBreakpoints:true,responsiveBreakpoints:{portrait:{changePoint:480,visibleItems:1},landscape:{changePoint:640,visibleItems:2},tablet:{changePoint:768,visibleItems:3}}});}
if($('#DateCountdown').length){$("#DateCountdown").TimeCircles();}});